const $=id=>document.getElementById(id);let data,currentTab='menu';const params=new URLSearchParams(location.hash.slice(1));const invitationToken=params.get('invite');history.replaceState(null,'',location.pathname);$('pin').value=localStorage.getItem('relayPin')||'';
function notify(text){$('message').textContent=text;}
function deviceId(){let id=localStorage.getItem('relayDeviceId');if(!id){id=crypto.randomUUID();localStorage.setItem('relayDeviceId',id);}return id;}
async function api(body){const response=await fetch('/api/administrations',{method:body?'POST':'GET',headers:{'content-type':'application/json','x-app-pin':$('pin').value.trim(),'x-device-id':deviceId(),'x-device-name':localStorage.getItem('relayDeviceName')||'Celular Android'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo completar.');return result;}
function selectedGroup(){return data.role==='super_master'?$('group').value:data.groupId;}
function node(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n;}
function button(label,action){const b=node('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await action();}catch(e){notify(e.message);}finally{b.disabled=false;}};return b;}
function timerMode(input){const label=node('label','Modo de funcionamiento'),select=node('select');for(const [value,text] of [['timed','Con temporizador'],['manual','Sin temporizador (ON/OFF)']]){const option=node('option',text);option.value=value;select.append(option);}select.value=Number(input.value)>0?'timed':'manual';input.disabled=select.value==='manual';select.onchange=()=>{input.disabled=select.value==='manual';if(!input.disabled&&Number(input.value)===0)input.value=4;};label.append(select);return {label,value:()=>select.value==='manual'?0:Number(input.value)};}
function groups(select,value){select.replaceChildren();if(data.role==='super_master'){const own=node('option','Máster general');own.value='master';select.append(own);}for(const g of data.groups){const option=node('option',g.name+' · '+g.status);option.value=g.id;select.append(option);}select.value=value||select.options[0]?.value||'';}
async function load(){const old=$('group').value;data=await api();$('access').hidden=true;$('panelToolbar').hidden=false;$('groupLabel').hidden=data.role!=='super_master';groups($('group'),old);$('role').querySelector('[value=admin]').hidden=data.role!=='super_master';if(data.role!=='super_master')$('role').value='user';$('add').hidden=data.role!=='super_master';if(data.role==='user')currentTab='equipment';render();}
function render(){const management=data.role!=='user';const master=data.role==='super_master';if(!master&&currentTab==='timers')currentTab='menu';$('tabs').hidden=currentTab!=='menu';$('groupLabel').hidden=!master||currentTab==='menu';$('timers').hidden=!master||currentTab!=='timers';$('tabs').querySelector('[data-tab=timers]').hidden=!master;$('openMenu').textContent=master?'☰ Menú Máster':'☰ Menú';$('viewTitle').textContent=({menu:'Menú',people:'Administradores y usuarios',equipment:'Actuadores',timers:'Temporizadores'})[currentTab];$('timerCards').replaceChildren();$('title').textContent=data.role==='super_master'?'Máster general':management?'Mi administración':'Mis actuadores';$('people').hidden=!management||currentTab!=='people';$('equipment').hidden=currentTab!=='equipment';$('tabs').querySelector('[data-tab=people]').hidden=!management;
  $('users').replaceChildren();if(data.role==='super_master'){for(const admin of data.groups){const row=node('article');row.append(node('strong','Administrador: '+admin.name),node('small',admin.status));for(const [label,status] of [['Pausar','paused'],['Bloquear','blocked'],['Reactivar','active']])row.append(button(label,async()=>{await api({action:'accountStatus',userId:admin.accountId,status});notify('Estado del administrador guardado.');await load();}));$('users').append(row);}}for(const user of data.users.filter(u=>u.groupId===selectedGroup())){const card=node('article');card.append(node('strong',user.name),node('small',user.phone+' · '+user.status));const apartmentLabel=node('label','Departamento'),apartment=node('input');apartment.maxLength=30;apartment.value=user.apartment||'';apartmentLabel.append(apartment);card.append(apartmentLabel);const permissions=node('div');for(const item of data.actuators.filter(a=>a.groupId===user.groupId)){const label=node('label'),input=node('input');input.type='checkbox';input.value=item.id;input.checked=user.actuatorIds.includes(item.id);label.append(input,document.createTextNode(item.name));permissions.append(label);}card.append(permissions,button('Guardar accesos',async()=>{await api({action:'permissions',userId:user.id,groupId:user.groupId,apartment:apartment.value,actuatorIds:[...permissions.querySelectorAll('input:checked')].map(i=>i.value)});notify('Accesos guardados.');await load();}));for(const [label,status] of [['Pausar','paused'],['Bloquear','blocked'],['Reactivar','active']])card.append(button(label,async()=>{await api({action:'accountStatus',userId:user.id,status});notify('Estado del usuario guardado.');await load();}));$('users').append(card);}
  $('actuators').replaceChildren();for(const item of data.actuators.filter(a=>data.role==='user'||a.groupId===selectedGroup())){const card=node('article');card.append(node('h3',item.name));const state=node('div','Estado pendiente');state.className='state';const read=async()=>{const r=await api({action:'status',id:item.id});state.textContent=r.state===true?'ON':r.state===false?'OFF':'Estado pendiente';};card.append(state,button('ON',async()=>{await api({action:'control',id:item.id,state:true});notify('Orden ON enviada.');await read();}),button('OFF',async()=>{await api({action:'control',id:item.id,state:false});notify('Orden OFF enviada.');await read();}),button('Actualizar estado',read));
    card.append(node('small',item.timerSeconds?'Apagado automático: '+item.timerSeconds+' segundos':'Modo manual ON/OFF'));
    if(data.role==='super_master'){const card=node('article');card.append(node('h3',item.name));$('timerCards').append(card);const label=node('label','Apagado automático, segundos (0 = manual)'),input=node('input');input.type='number';input.min='0';input.max=item.timer?.max||0;input.value=item.timerSeconds;const mode=timerMode(input);label.append(input);card.append(mode.label,label);if(!item.timer)card.append(node('small','Este equipo no informa un temporizador compatible.'));card.append(button('Guardar temporizador',async()=>{await api({action:'settings',id:item.id,name:item.name,timerSeconds:mode.value()});notify('Temporizador guardado.');await load();}));}
    if(data.role==='super_master'){const label=node('label','Administrador responsable'),select=node('select');groups(select,item.groupId);label.append(select);card.append(label,button('Asignar administrador',async()=>{await api({action:'assign',id:item.id,groupId:select.value});notify('Asignación guardada.');await load();}));}
    $('actuators').append(card);
  }
  if(data.role==='super_master'&&selectedGroup()==='master')for(const item of data.originalActuators||[]){const card=node('article');card.append(node('h3',item.name+' · inicio'),node('small','Apagado automático: '+item.timerSeconds+' segundos'));const label=node('label','Apagado automático, segundos (0 = manual)'),input=node('input');input.type='number';input.min='0';input.max=item.timer?.max||86400;input.step=item.timer?.step||1;input.value=item.timerSeconds;const mode=timerMode(input);label.append(input);card.append(mode.label,label);if(!item.timer)card.append(node('small',item.error||'El equipo no informa un temporizador compatible. Las activaciones automáticas requieren compatibilidad.'));card.append(button('Guardar temporizador',async()=>{await api({action:'originalSettings',relay:item.relay,timerSeconds:mode.value()});notify('Temporizador guardado.');await load();}));$('timerCards').append(card);}
  if(!$('timerCards').children.length)$('timerCards').append(node('p','No hay actuadores en esta administración.'));
  if(!$('actuators').children.length)$('actuators').append(node('p','Todavía no hay actuadores asignados.'));
}
$('access').onsubmit=async e=>{e.preventDefault();try{if(invitationToken){await api({action:'claim',token:invitationToken});notify('Invitación aceptada.');}localStorage.setItem('relayPin',$('pin').value.trim());await load();}catch(error){notify(error.message);}};
$('group').onchange=()=>{$('invitation').hidden=true;render();};for(const b of $('tabs').querySelectorAll('button'))b.onclick=()=>{currentTab=b.dataset.tab;render();window.scrollTo(0,0);};
$('openMenu').onclick=()=>{currentTab='menu';render();window.scrollTo(0,0);};
$('invite').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const result=await api({action:'invite',role:$('role').value,name:$('name').value,phone:$('phone').value,apartment:$('apartment').value,groupId:selectedGroup()});$('inviteLink').value=location.origin+'/administracion.html#invite='+result.token;$('invitation').hidden=false;notify('Invitación creada.');}catch(error){notify(error.message);}finally{b.disabled=false;}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('inviteLink').value);notify('Enlace copiado.');}catch{$('inviteLink').select();notify('Selecciona y copia el enlace.');}};
const addMode=timerMode($('timer'));$('timer').parentElement.before(addMode.label);
$('add').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api({action:'add',name:$('actuatorName').value,deviceId:$('deviceId').value,code:$('channel').value,timerSeconds:addMode.value(),groupId:selectedGroup()});notify('Actuador agregado y asignado.');await load();}catch(error){notify(error.message);}finally{b.disabled=false;}};
$('refresh').onclick=async()=>{const b=$('refresh');b.disabled=true;try{for(const button of $('actuators').querySelectorAll('button'))if(button.textContent==='Actualizar estado')await button.onclick();}finally{b.disabled=false;}};
if(!invitationToken&&$('pin').value)load().catch(e=>notify(e.message));else if(invitationToken)notify('Ingresa el PIN para aceptar tu invitación personal.');
