const pinInput = document.getElementById("pin");
const savePin = document.getElementById("savePin");
const refresh = document.getElementById("refresh");
const message = document.getElementById("message");
const buttons = [...document.querySelectorAll(".power")];
const adminPanel = document.getElementById("adminPanel");
const deviceList = document.getElementById("deviceList");
const refreshDevices = document.getElementById("refreshDevices");
const states = {1:null,2:null,3:null};
function getDeviceId(){let id=localStorage.getItem("relayDeviceId");if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`).replace(/[^a-zA-Z0-9-]/g,"");localStorage.setItem("relayDeviceId",id);}return id;}
function getDeviceName(){let name=localStorage.getItem("relayDeviceName");if(!name){name=`Celular ${navigator.platform||"Android"}`;localStorage.setItem("relayDeviceName",name);}return name;}
pinInput.value=localStorage.getItem("relayPin")||"";
function pin(){return pinInput.value.trim();}
function show(text,error=false){message.textContent=text;message.style.color=error?"#fecaca":"#bfd3e2";}
function paint(relay,value){states[relay]=value;const card=document.querySelector(`.relay-card[data-relay="${relay}"]`);const label=document.getElementById(`state${relay}`);card.classList.toggle("on",value===true);label.textContent=value===true?"ENCENDIDO":value===false?"APAGADO":"Sin conexión";}
function setRelayAccess(allowed){for(const relay of [1,2,3]){const permitted=allowed.includes(relay);const card=document.querySelector(`.relay-card[data-relay="${relay}"]`);const button=card.querySelector(".power");card.classList.toggle("denied",!permitted);button.disabled=!permitted;if(!permitted){states[relay]=null;document.getElementById(`state${relay}`).textContent="Sin permiso";}}}
async function api(url,options={}){const headers={...(options.headers||{}),"x-app-pin":pin(),"x-device-id":getDeviceId(),"x-device-name":getDeviceName()};const res=await fetch(url,{...options,headers});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"No se pudo completar la operación");return data;}
async function loadStatus(){if(!pin()){show("Ingresa tu PIN de acceso.",true);return;}refresh.disabled=true;try{const data=await api("/api/status");setRelayAccess(data.allowedRelays||[]);const errors=[];for(const item of data.relays){paint(item.relay,item.state);if(item.error)errors.push(`Relé ${item.relay}: ${item.error}`);}adminPanel.hidden=data.role!=="master";if(data.role==="master")loadDevices();if(errors.length)show(errors.join(" · "),true);else show(data.role==="master"?"Este equipo es Master.":"Estado actualizado.");}catch(e){show(e.message,true);}finally{refresh.disabled=false;}}
savePin.addEventListener("click",()=>{localStorage.setItem("relayPin",pin());show("PIN guardado en este teléfono.");loadStatus();});
refresh.addEventListener("click",loadStatus);
buttons.forEach(btn=>btn.addEventListener("click",async()=>{const relay=Number(btn.dataset.relay);if(!pin()){show("Ingresa tu PIN de acceso.",true);return;}const desired=states[relay]!==true;btn.disabled=true;show(`${desired?"Encendiendo":"Apagando"} relé ${relay}…`);try{const data=await api("/api/control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({relay,state:desired})});paint(relay,Boolean(data.state));show(`Relé ${relay}: ${data.state?"encendido":"apagado"}.`);}catch(e){show(e.message,true);}finally{btn.disabled=false;}}));
async function loadDevices(){try{const data=await api("/api/devices");deviceList.innerHTML="";for(const device of data.devices){const row=document.createElement("div");row.className="device-row";const info=document.createElement("div");const title=document.createElement("strong");title.textContent=device.name;const detail=document.createElement("small");detail.textContent=device.role==="master"?"Este equipo · Master":"Equipo autorizado";if(device.role!=="master")detail.textContent=device.status==="pending"?"Pendiente de autorización":`Acceso: ${(device.relays||[]).map(n=>`Relé ${n}`).join(", ")}`;info.append(title,detail);row.append(info);if(device.role!=="master"){const permissions=document.createElement("div");permissions.className="device-permissions";for(const relay of [1,2,3]){const label=document.createElement("label");const checkbox=document.createElement("input");checkbox.type="checkbox";checkbox.value=relay;checkbox.checked=(device.relays||[]).includes(relay);label.append(checkbox,document.createTextNode(` Relé ${relay}`));permissions.append(label);}const save=document.createElement("button");save.className="save-permissions";save.textContent=device.status==="pending"?"Autorizar":"Guardar permisos";save.addEventListener("click",async()=>{const relays=[...permissions.querySelectorAll('input:checked')].map(input=>Number(input.value));if(!relays.length){show("Selecciona por lo menos un relé.",true);return;}save.disabled=true;try{await api("/api/devices",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({deviceId:device.id,relays})});show(`Permisos guardados para ${device.name}.`);await loadDevices();}catch(e){show(e.message,true);save.disabled=false;}});const remove=document.createElement("button");remove.className="remove-device";remove.textContent="Eliminar";remove.addEventListener("click",async()=>{if(!confirm(`¿Eliminar el acceso de ${device.name}?`))return;remove.disabled=true;try{await api("/api/devices",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({deviceId:device.id})});show(`${device.name} quedó sin acceso.`);await loadDevices();}catch(e){show(e.message,true);remove.disabled=false;}});const actions=document.createElement("div");actions.className="device-actions";actions.append(save,remove);row.append(permissions,actions);}deviceList.append(row);}}catch(e){show(e.message,true);}}
refreshDevices.addEventListener("click",loadDevices);
if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
if(pin())loadStatus();
