const $=id=>document.getElementById(id);
let payload=null,current=null,previewRole='admin';
function deviceId(){let id=localStorage.getItem('relayDeviceId');if(!id){id=crypto.randomUUID();localStorage.setItem('relayDeviceId',id);}return id;}
function headers(){return {'content-type':'application/json','x-app-pin':localStorage.getItem('relayPin')||'','x-device-id':deviceId(),'x-device-name':localStorage.getItem('relayDeviceName')||'PC Máster'};}
async function api(body){const response=await fetch('/api/app-matrix',{method:body?'POST':'GET',headers:headers(),...(body?{body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'No se pudo completar.');return data;}
function message(text,error=false){$('message').textContent=text;$('message').dataset.error=String(error);}
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function check(checked){const input=document.createElement('input');input.type='checkbox';input.checked=Boolean(checked);input.addEventListener('change',renderPreview);return input;}
function number(value){const input=document.createElement('input');input.type='number';input.className='order';input.min='1';input.max='99';input.value=value||1;input.addEventListener('input',renderPreview);return input;}
function selected(){return payload?.groups?.find(group=>group.id===$('group').value)||null;}
function moduleRow(item){const row=el('div',undefined,'module-row');row.dataset.id=item.id;const label=document.createElement('input');label.className='module-label';label.maxLength=60;label.value=item.label;label.addEventListener('input',renderPreview);const enabled=check(item.enabled),admin=check(item.adminVisible),user=check(item.userVisible),order=number(item.order);enabled.dataset.field='enabled';admin.dataset.field='adminVisible';user.dataset.field='userVisible';order.dataset.field='order';label.dataset.field='label';row.append(label,enabled,admin,user,order);return row;}
function actuatorRow(device,config){const saved=(config.actuators||[]).find(item=>item.id===device.id)||{id:device.id,label:device.name,enabled:true,adminVisible:true,userVisible:true,order:(config.actuators||[]).length+1};const row=el('div',undefined,'actuator-row');row.dataset.id=device.id;const enabled=check(saved.enabled);enabled.dataset.field='enabled';const label=document.createElement('input');label.className='actuator-label';label.value=saved.label||device.name;label.maxLength=60;label.dataset.field='label';label.addEventListener('input',renderPreview);const admin=check(saved.adminVisible);admin.dataset.field='adminVisible';const user=check(saved.userVisible);user.dataset.field='userVisible';const order=number(saved.order);order.dataset.field='order';row.append(enabled,label,admin,user,order);return row;}
function loadGroup(){const group=selected();if(!group)return;current=JSON.parse(JSON.stringify(group.draft||group.published));$('appName').value=current.branding?.appName||'A&N Control';$('communityName').value=current.branding?.communityName||group.name;$('adminStatus').textContent=group.status==='deleted'?'ELIMINADO':String(group.status||'active').toUpperCase();$('modules').replaceChildren(...(current.modules||[]).map(moduleRow));$('actuators').replaceChildren(...(group.actuators||[]).map(device=>actuatorRow(device,current)));if(!(group.actuators||[]).length)$('actuators').append(el('p','No hay actuadores asignados todavía.'));const deleted=group.status==='deleted';$('saveDraft').disabled=deleted;$('publish').disabled=deleted;$('deleteAdmin').hidden=deleted;$('restoreAdmin').hidden=!deleted;renderPreview();}
function collect(){const group=selected();return {...(current||{}),groupId:group.id,branding:{appName:$('appName').value.trim()||'A&N Control',communityName:$('communityName').value.trim()||group.name},modules:[...$('modules').children].filter(row=>row.dataset.id).map(row=>({id:row.dataset.id,...Object.fromEntries([...row.querySelectorAll('[data-field]')].map(input=>[input.dataset.field,input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value]))})),actuators:[...$('actuators').children].filter(row=>row.dataset.id).map(row=>({id:row.dataset.id,...Object.fromEntries([...row.querySelectorAll('[data-field]')].map(input=>[input.dataset.field,input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value]))}))};}
function renderPreview(){if(!selected())return;const config=collect(),key=previewRole==='user'?'userVisible':'adminVisible';$('preview').replaceChildren();$('preview').append(el('div',config.branding.communityName||config.branding.appName,'preview-title'));const grid=el('div',undefined,'preview-grid');for(const item of [...config.modules,...config.actuators].filter(item=>item.enabled&&item[key]).sort((a,b)=>(a.order||99)-(b.order||99)))grid.append(el('div',item.label,'preview-item'));if(!grid.children.length)grid.append(el('p','No hay ventanas visibles para este perfil.'));$('preview').append(grid);}
function renderGroups(){$('group').replaceChildren();for(const group of payload.groups||[]){const option=el('option',group.name+(group.status==='deleted'?' · ELIMINADO':' · '+group.status));option.value=group.id;$('group').append(option);}$('editor').hidden=!payload.groups?.length;if(payload.groups?.length)loadGroup();else message('Todavía no hay administradores. Crea el primero desde Administración general.');}
async function save(action){const group=selected();if(!group)return;const button=action==='publish'?$('publish'):$('saveDraft');button.disabled=true;try{const result=await api({action,groupId:group.id,config:collect()});group.draft=result.config;if(action==='publish')group.published=result.config;current=JSON.parse(JSON.stringify(result.config));message(action==='publish'?'Cambios publicados. La configuración ya está disponible para esta comunidad.':'Borrador guardado.');}catch(error){message(error.message,true);}finally{button.disabled=false;}}
$('group').addEventListener('change',loadGroup);$('appName').addEventListener('input',renderPreview);$('communityName').addEventListener('input',renderPreview);
for(const button of document.querySelectorAll('[data-preview]'))button.addEventListener('click',()=>{previewRole=button.dataset.preview;for(const item of document.querySelectorAll('[data-preview]'))item.classList.toggle('active',item===button);renderPreview();});
$('saveDraft').onclick=()=>save('saveDraft');$('publish').onclick=()=>save('publish');
$('deleteAdmin').onclick=async()=>{const group=selected();if(!group||!confirm('¿Eliminar este administrador y suspender su comunidad? Los datos se conservarán para poder restaurarla.'))return;try{await api({action:'deleteAdministration',groupId:group.id});group.status='deleted';group.published.status='deleted';group.draft.status='deleted';message('Administrador eliminado. Los datos quedaron conservados.');loadGroup();}catch(error){message(error.message,true);}};
$('restoreAdmin').onclick=async()=>{const group=selected();if(!group)return;try{await api({action:'restoreAdministration',groupId:group.id});group.status='active';group.published.status='active';group.draft.status='active';message('Administrador restaurado. Sus usuarios quedaron en pausa para revisión.');loadGroup();}catch(error){message(error.message,true);}};
(async()=>{try{if(!localStorage.getItem('relayPin'))throw new Error('Primero entra a Administración general con tu PIN.');payload=await api();if(payload.role!=='super_master')throw new Error('Solo el Máster general puede abrir el Constructor de App.');renderGroups();}catch(error){message(error.message,true);$('editor').hidden=true;}})();