(()=>{
  const host=document.querySelector('main')||document.body;const panel=document.createElement('section');panel.className='panic-panel';panel.hidden=true;
  panel.innerHTML='<h2>Botón de pánico</h2><label id="panicGroupLabel" hidden>Administración de la alerta<select id="panicGroup"></select></label><p id="panicHelp"></p><button type="button" id="panicSound">Activar sonido de alertas SOS</button><p id="panicSoundStatus" role="status"></p><button type="button" id="panicPush">Activar avisos de Información y Emergencias con AYN cerrada</button><p id="panicPushStatus" role="status"></p><button type="button" class="panic-trigger" id="panicTrigger" aria-label="SOS: activar alerta de pánico">SOS</button><p class="panic-status" id="panicStatus" role="status" aria-live="polite"></p><details id="panicConfig" hidden><summary>Configurar actuador de pánico</summary><label>Actuador asignado<select id="panicActuator"></select></label><button type="button" id="panicSave">Guardar actuador de pánico</button></details><div id="panicEvents" aria-live="polite"></div>';
  const message=document.getElementById('message');if(message)message.after(panel);else host.append(panel);
  const applyMenuView=()=>{const view=location.pathname.endsWith('administracion.html')?document.body.dataset.adminView:document.body.dataset.userView;panel.hidden=view!=='panic';};
  document.addEventListener('ayn-menu-view',()=>queueMicrotask(applyMenuView));
  const trigger=panel.querySelector('#panicTrigger');
  trigger.hidden=true;trigger.disabled=true;document.body.append(trigger);
  const sosScreen=document.createElement('dialog');sosScreen.className='panic-screen';sosScreen.hidden=true;sosScreen.setAttribute('role','dialog');sosScreen.setAttribute('aria-modal','true');sosScreen.setAttribute('aria-label','Alerta SOS activada');
  sosScreen.innerHTML='<div class="panic-watermark" aria-hidden="true">SOS</div><div class="panic-screen-content"><h2>SOS</h2><p class="panic-screen-countdown" aria-live="off"></p><p class="panic-screen-status" role="status" aria-live="polite"></p><button type="button" class="panic-screen-apology" hidden>Activación accidental: enviar disculpa</button><button type="button" class="panic-screen-close">Volver a la app</button></div>';document.body.append(sosScreen);
  const screenStatus=sosScreen.querySelector('.panic-screen-status'),screenClose=sosScreen.querySelector('.panic-screen-close'),screenApology=sosScreen.querySelector('.panic-screen-apology');let screenEvent=null,previousFocus,screenExpires=0;const screenCountdown=sosScreen.querySelector(".panic-screen-countdown");
  const closeScreen=()=>{screenExpires=0;sosScreen.close?.();sosScreen.hidden=true;document.body.classList.remove('panic-screen-open');previousFocus?.focus();};
  const finishScreen=()=>{screenExpires=0;sosScreen.classList.add('panic-screen-ended');screenCountdown.textContent='Alerta cancelada';};
  const openScreen=()=>{sosScreen.classList.remove('panic-screen-ended');previousFocus=document.activeElement;screenEvent=null;screenApology.hidden=true;screenStatus.textContent='Enviando alerta…';screenExpires=Date.now()+300000;sosScreen.hidden=false;try{if(typeof sosScreen.showModal==='function'&&!sosScreen.open)sosScreen.showModal();}catch{ /* Fixed overlay remains available when native modal is unavailable. */ }document.body.classList.add('panic-screen-open');screenClose.focus();updateCountdown();};
  const updateCountdown=()=>{if(sosScreen.hidden||!screenExpires)return;const remaining=Math.max(0,Math.ceil((screenExpires-Date.now())/1000));screenCountdown.textContent='Alerta visual · '+Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');if(!remaining)closeScreen();};setInterval(updateCountdown,1000);
  sosScreen.addEventListener('cancel',e=>{e.preventDefault();closeScreen();});
  screenClose.onclick=closeScreen;
  sosScreen.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeScreen();}if(event.key==='Tab'){const focusable=[screenApology,screenClose].filter(b=>!b.hidden&&!b.disabled);if(focusable.length){event.preventDefault();const index=focusable.indexOf(document.activeElement);focusable[(index+(event.shiftKey?-1:1)+focusable.length)%focusable.length].focus();}}});
  screenApology.onclick=async()=>{if(!screenEvent)return;screenApology.disabled=true;try{await api({action:'apologize',eventId:screenEvent});screenStatus.textContent='Activación accidental. Disculpa enviada a esta administración.';screenApology.hidden=true;finishScreen();status(screenStatus.textContent);await load();}catch(e){screenStatus.textContent='No se pudo enviar la disculpa: '+e.message;}finally{screenApology.disabled=false;}};
  const el=id=>id==='panicTrigger'?trigger:panel.querySelector('#'+id);let groupId='',role='',loading=false,sending=false,configured=false,accessRestricted=false,requestId=null,seen=new Map();
  let soundContext=null,soundEnabled=false,activeAlerts=[],lastSound=0,soundNodes=[];
  const stopSound=()=>{for(const oscillator of soundNodes){try{oscillator.stop();}catch{}}soundNodes=[];};
  const playSound=()=>{const current=activeAlerts.filter(e=>e.active!==false&&!e.apology&&!e.isOwn&&Date.parse(e.expiresAt||new Date(Date.parse(e.createdAt)+300000).toISOString())>Date.now());if(!current.length){stopSound();return;}if(!soundEnabled||soundContext?.state!=='running'||Date.now()-lastSound<8000)return;lastSound=Date.now();stopSound();for(let i=0;i<3;i++){const oscillator=soundContext.createOscillator(),gain=soundContext.createGain(),start=soundContext.currentTime+i*.3;oscillator.frequency.value=i%2?660:880;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.15,start+.02);gain.gain.linearRampToValueAtTime(0,start+.22);oscillator.connect(gain);gain.connect(soundContext.destination);oscillator.start(start);oscillator.stop(start+.24);soundNodes.push(oscillator);}};
  const enableSound=async()=>{try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('Sonido no disponible en este navegador.');soundContext=soundContext||new Audio();await soundContext.resume();soundEnabled=soundContext.state==='running';el('panicSound').textContent=soundEnabled?'Sonido SOS activado ✓':'Activar sonido de alertas SOS';el('panicSoundStatus').textContent=soundEnabled?'Aviso sonoro cada 8 segundos mientras haya una alerta activa y AYN esté abierta.':'Toca para permitir el sonido.';playSound();}catch(e){el('panicSoundStatus').textContent=e.message;}};
  el('panicSound').onclick=()=>{localStorage.setItem('aynPanicSound','enabled');return enableSound();};
  document.addEventListener('pointerdown',()=>{if(localStorage.getItem('aynPanicSound')==='enabled'&&!soundEnabled)enableSound();});
  setInterval(playSound,1000);
  const pushButton=el('panicPush'),pushStatus=el('panicPushStatus'),settingsPushButton=document.getElementById('panicSettingsPush'),settingsPushStatus=document.getElementById('panicSettingsStatus');
  const pushButtons=[pushButton,settingsPushButton].filter(Boolean),pushStatuses=[pushStatus,settingsPushStatus].filter(Boolean);
  const pushLabel=()=>{const enabled=localStorage.getItem('aynPanicPush')==='enabled';for(const button of pushButtons)button.textContent=enabled?'Desactivar Información y Emergencias':'Activar Información y Emergencias';};pushLabel();
  const setPushStatus=text=>{for(const item of pushStatuses)item.textContent=text;};
  async function pushApi(body){const response=await fetch('/api/panic-subscription',{method:body?'POST':'GET',headers:{'content-type':'application/json','x-app-pin':document.getElementById('pin')?.value.trim()||localStorage.getItem('relayPin')||'','x-device-id':localStorage.getItem('relayDeviceId')||''},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo guardar la preferencia.');return data;}
  const togglePush=async()=>{for(const button of pushButtons)button.disabled=true;try{if(!('Notification' in window)||!('serviceWorker' in navigator)||!('PushManager' in window))throw new Error('Este navegador no admite notificaciones con AYN cerrada.');const registration=await navigator.serviceWorker.ready;if(localStorage.getItem('aynPanicPush')==='enabled'){await pushApi({action:'disable'});await (await registration.pushManager.getSubscription())?.unsubscribe();localStorage.removeItem('aynPanicPush');setPushStatus('Avisos de Información y Emergencias desactivados en este equipo.');}else{const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Permite las notificaciones en los ajustes del navegador para activarlas.');const {publicKey}=await pushApi();const bytes=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-publicKey.length%4)%4)),c=>c.charCodeAt(0));const subscription=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await pushApi({action:'subscribe',subscription:subscription.toJSON()});localStorage.setItem('aynPanicPush','enabled');setPushStatus('Avisos de Información y Emergencias activados. También llegarán con AYN cerrada cuando el sistema lo permita.');}pushLabel();}catch(e){setPushStatus(e.message);}finally{for(const button of pushButtons)button.disabled=false;}};
  for(const button of pushButtons)button.onclick=togglePush;
  const showSOS=visible=>{trigger.hidden=!visible;document.body.classList.toggle('panic-sos-visible',visible);};
  const status=text=>{el('panicStatus').textContent=text;document.dispatchEvent(new Event('ayn-panic-feedback'));};
  const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
  async function api(body){const pin=document.getElementById('pin')?.value.trim()||localStorage.getItem('relayPin')||'',id=localStorage.getItem('relayDeviceId');if(!pin||!id)throw new Error('Ingresa tu PIN para acceder.');const response=await fetch('/api/panic'+(body?'':'?groupId='+encodeURIComponent(groupId)),{method:body?'POST':'GET',headers:{'content-type':'application/json','x-app-pin':pin,'x-device-id':id,'x-device-name':localStorage.getItem('relayDeviceName')||'Celular Android'},...(body?{body:JSON.stringify({...body,groupId})}:{})});const data=await response.json();if(!response.ok){if(data.accessStatus){accessRestricted=true;document.dispatchEvent(new CustomEvent('ayn-access-restricted',{detail:data.error}));}throw Object.assign(new Error(data.error||'No se pudo completar.'),{status:response.status});}if(accessRestricted){accessRestricted=false;document.dispatchEvent(new Event('ayn-access-restored'));}return data;}
  async function load(){if(loading||document.hidden)return;loading=true;try{const data=await api();role=data.role;groupId=data.groupId;applyMenuView();showSOS(true);el('panicGroupLabel').hidden=role!=='super_master';const select=el('panicGroup');select.replaceChildren();for(const g of data.groups){const o=node('option',g.name);o.value=g.id;select.append(o);}select.value=groupId;configured=Boolean(data.configured);trigger.disabled=sending;trigger.title=configured?'SOS: alertar a '+(data.groups.find(g=>g.id===groupId)?.name||'tu administración'):'SOS: enviar alerta a tu administración; sin sirena asignada';el('panicHelp').textContent=data.configured?'Activa '+data.actuatorName+' y avisa a los usuarios de esta administración con AYN abierta. Los avisos se actualizan cada 3 segundos.':'SOS enviará el aviso a esta administración. El Máster todavía no ha asignado una sirena.';el('panicConfig').hidden=role!=='super_master';const actuator=el('panicActuator'),selected=actuator.value;actuator.replaceChildren();for(const a of data.actuators){const o=node('option',a.name);o.value=a.id;actuator.append(o);}if([...actuator.options].some(o=>o.value===selected))actuator.value=selected;el('panicSave').disabled=!actuator.options.length;
    activeAlerts=data.events;playSound();const ownScreen=data.events.find(e=>e.id===screenEvent);if(ownScreen?.apology&&!sosScreen.hidden){finishScreen();screenApology.hidden=true;screenStatus.textContent='Alerta cancelada. Disculpa enviada a esta administración.';}
    const events=el('panicEvents');events.replaceChildren();for(const event of data.events){const card=node('article','');card.className='panic-event'+(event.apology?' panic-apology':'');card.append(node('strong',event.apology?'Activación accidental':event.active===false?'Alerta finalizada':'ALERTA DE PÁNICO'),node('p',event.message),node('small',event.name+' · '+new Date(event.createdAt).toLocaleString('es-CL')));card.append(node('p','Teléfono: '+(event.phone||'sin registrar')+' · Departamento: '+(event.apartment||'sin registrar')));card.append(node('p',event.actuatorStatus==='sent'?'Orden enviada a '+event.actuatorName+'.':event.actuatorStatus==='failed'?'La alerta fue emitida, pero no se pudo activar el actuador.':event.actuatorStatus==='not-configured'?'Aviso enviado; sin sirena asignada.':'Activación del actuador pendiente.'));if(event.apology)card.append(node('p',event.apology.message),node('small',event.apology.name+' · '+new Date(event.apology.at).toLocaleString('es-CL')));else if(event.canApologize){const button=node('button','Activación accidental: enviar disculpa');button.type='button';button.onclick=async()=>{button.disabled=true;try{await api({action:'apologize',eventId:event.id});if(screenEvent===event.id)finishScreen();status('Disculpa enviada a esta administración.');await load();}catch(e){status(e.message);button.disabled=false;}};card.append(button);}if(['admin','super_master'].includes(role)&&(event.apology||event.active===false)){const remove=node('button','Eliminar');remove.type='button';remove.setAttribute('aria-label','Eliminar aviso de '+event.name);remove.onclick=async()=>{remove.disabled=true;try{await api({action:'dismiss',eventId:event.id});card.remove();status('Aviso eliminado de tu bandeja.');await load();}catch(e){status(e.message);remove.disabled=false;}};card.append(remove);}events.append(card);seen.set(event.id,Boolean(event.apology));}
  }catch(e){if([401,403].includes(e.status)){activeAlerts=[];stopSound();panel.hidden=true;showSOS(false);configured=false;trigger.disabled=true;}else if(!panel.hidden)status('No se pudieron actualizar las alertas. Revisa tu conexión.');}finally{loading=false;}}
  el('panicGroup').onchange=()=>{groupId=el('panicGroup').value;requestId=null;seen.clear();activeAlerts=[];stopSound();el('panicEvents').replaceChildren();el('panicTrigger').disabled=true;status('');load();};
  el('panicSave').onclick=async()=>{const b=el('panicSave');b.disabled=true;try{await api({action:'configure',actuatorId:el('panicActuator').value});status('Actuador de pánico guardado.');await load();}catch(e){status(e.message);}finally{b.disabled=false;}};
  el('panicTrigger').onclick=async()=>{const b=el('panicTrigger');if(sending)return;sending=true;b.disabled=true;b.setAttribute('aria-busy','true');openScreen();try{requestId=requestId||(crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join(''));const r=await api({action:'trigger',requestId});status(r.message||'Alerta ya registrada.');screenStatus.textContent=r.message||'Alerta ya registrada.';screenEvent=r.eventId;screenApology.hidden=!screenEvent;if(r.expiresAt)screenExpires=Date.parse(r.expiresAt);updateCountdown();requestId=null;await load();}catch(e){screenStatus.textContent='No se confirmó la alerta: '+e.message+' Vuelve a la app para reintentar.';status(screenStatus.textContent);}finally{sending=false;b.disabled=accessRestricted;b.removeAttribute('aria-busy');}};
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(load,3000);load();
})();
