(()=>{
  const host=document.querySelector('main')||document.body;const panel=document.createElement('section');panel.className='panic-panel';panel.hidden=true;
  panel.innerHTML='<h2>Botón de pánico</h2><label id="panicGroupLabel" hidden>Administración de la alerta<select id="panicGroup"></select></label><p id="panicHelp"></p><button type="button" class="panic-trigger" id="panicTrigger" aria-label="SOS: activar alerta de pánico">SOS</button><p class="panic-status" id="panicStatus" role="status" aria-live="polite"></p><details id="panicConfig" hidden><summary>Configurar actuador de pánico</summary><label>Actuador asignado<select id="panicActuator"></select></label><button type="button" id="panicSave">Guardar actuador de pánico</button></details><div id="panicEvents" aria-live="polite"></div>';
  const message=document.getElementById('message');if(message)message.after(panel);else host.append(panel);
  const trigger=panel.querySelector('#panicTrigger');
  trigger.hidden=true;trigger.disabled=true;document.body.append(trigger);
  const el=id=>id==='panicTrigger'?trigger:panel.querySelector('#'+id);let groupId='',role='',loading=false,sending=false,configured=false,accessRestricted=false,requestId=null,seen=new Map();
  const showSOS=visible=>{trigger.hidden=!visible;document.body.classList.toggle('panic-sos-visible',visible);};
  const status=text=>el('panicStatus').textContent=text;
  const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
  async function api(body){const pin=document.getElementById('pin')?.value.trim()||localStorage.getItem('relayPin')||'',id=localStorage.getItem('relayDeviceId');if(!pin||!id)throw new Error('Ingresa tu PIN para acceder.');const response=await fetch('/api/panic'+(body?'':'?groupId='+encodeURIComponent(groupId)),{method:body?'POST':'GET',headers:{'content-type':'application/json','x-app-pin':pin,'x-device-id':id,'x-device-name':localStorage.getItem('relayDeviceName')||'Celular Android'},...(body?{body:JSON.stringify({...body,groupId})}:{})});const data=await response.json();if(!response.ok){if(data.accessStatus){accessRestricted=true;document.dispatchEvent(new CustomEvent('ayn-access-restricted',{detail:data.error}));}throw Object.assign(new Error(data.error||'No se pudo completar.'),{status:response.status});}if(accessRestricted){accessRestricted=false;document.dispatchEvent(new Event('ayn-access-restored'));}return data;}
  async function load(){if(loading||document.hidden)return;loading=true;try{const data=await api();role=data.role;groupId=data.groupId;panel.hidden=false;showSOS(true);el('panicGroupLabel').hidden=role!=='super_master';const select=el('panicGroup');select.replaceChildren();for(const g of data.groups){const o=node('option',g.name);o.value=g.id;select.append(o);}select.value=groupId;configured=Boolean(data.configured);trigger.disabled=sending||!configured;trigger.title=configured?'SOS: alertar a '+(data.groups.find(g=>g.id===groupId)?.name||'tu administración'):'El Máster debe configurar el actuador de pánico';el('panicHelp').textContent=data.configured?'Activa '+data.actuatorName+' y avisa a los usuarios de esta administración con AYN abierta. Los avisos se actualizan cada 15 segundos.':'El Máster debe asignar un actuador de pánico a esta administración.';el('panicConfig').hidden=role!=='super_master';const actuator=el('panicActuator'),selected=actuator.value;actuator.replaceChildren();for(const a of data.actuators){const o=node('option',a.name);o.value=a.id;actuator.append(o);}if([...actuator.options].some(o=>o.value===selected))actuator.value=selected;el('panicSave').disabled=!actuator.options.length;
    const events=el('panicEvents');events.replaceChildren();for(const event of data.events){const card=node('article','');card.className='panic-event'+(event.apology?' panic-apology':'');card.append(node('strong',event.apology?'Activación accidental':'ALERTA DE PÁNICO'),node('p',event.message),node('small',event.name+' · '+new Date(event.createdAt).toLocaleString('es-CL')));card.append(node('p','Teléfono: '+(event.phone||'sin registrar')+' · Departamento: '+(event.apartment||'sin registrar')));card.append(node('p',event.actuatorStatus==='sent'?'Orden enviada a '+event.actuatorName+'.':event.actuatorStatus==='failed'?'La alerta fue emitida, pero no se pudo activar el actuador.':'Activación del actuador pendiente.'));if(event.apology)card.append(node('p',event.apology.message),node('small',event.apology.name+' · '+new Date(event.apology.at).toLocaleString('es-CL')));else if(event.canApologize){const button=node('button','Activación accidental: enviar disculpa');button.type='button';button.onclick=async()=>{button.disabled=true;try{await api({action:'apologize',eventId:event.id});status('Disculpa enviada a esta administración.');await load();}catch(e){status(e.message);button.disabled=false;}};card.append(button);}events.append(card);seen.set(event.id,Boolean(event.apology));}
  }catch(e){if([401,403].includes(e.status)){panel.hidden=true;showSOS(false);configured=false;trigger.disabled=true;}else if(!panel.hidden)status('No se pudieron actualizar las alertas. Revisa tu conexión.');}finally{loading=false;}}
  el('panicGroup').onchange=()=>{groupId=el('panicGroup').value;requestId=null;seen.clear();el('panicEvents').replaceChildren();el('panicTrigger').disabled=true;status('');load();};
  el('panicSave').onclick=async()=>{const b=el('panicSave');b.disabled=true;try{await api({action:'configure',actuatorId:el('panicActuator').value});status('Actuador de pánico guardado.');await load();}catch(e){status(e.message);}finally{b.disabled=false;}};
  el('panicTrigger').onclick=async()=>{const b=el('panicTrigger');if(sending||!configured)return;sending=true;b.disabled=true;b.setAttribute('aria-busy','true');requestId=requestId||crypto.randomUUID();try{const r=await api({action:'trigger',requestId});status(r.message||'Alerta ya registrada.');requestId=null;await load();}catch(e){status('No se confirmó la alerta: '+e.message+' Puedes volver a intentar.');}finally{sending=false;b.disabled=!configured;b.removeAttribute('aria-busy');}};
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(load,15000);load();
})();
