const assert=require('node:assert/strict'),fs=require('node:fs');
const vm=require('node:vm');
const api=fs.readFileSync('api/administrations.js','utf8');
const html=fs.readFileSync('administracion.html','utf8'),admin=fs.readFileSync('administracion.js','utf8');
const app=fs.readFileSync('app.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
assert(html.includes('id="enrolledRelaySelect"'),'Selector de relés existentes');
assert(html.includes('id="relayAddManualFields"'),'Alta manual opcional');
assert(admin.includes("selection.startsWith('original:')"),'Original sin re-registro');
assert(admin.includes("selection.startsWith('managed:')"),'Gestionado sin re-registro');
assert(admin.includes("action:'assignOriginal'"),'Asignación original');
assert(admin.includes("action:'assign'"),'Asignación gestionada');
assert(admin.includes('renderEnrolledRelays()'),'Actualizar lista de registrados');
assert(api.includes("if(b.action==='assignOriginal')"),'Acción de Máster');
assert(api.includes("auth.role!=='super_master'"),'Control rol Máster');
assert(api.includes("A.updateRegistry(registry=>"),'Actualización atómica y autorizada');
assert(!api.includes('redis.call("HSET")'),'No registrar originales como nuevas entradas');
assert(app.includes('originalStatus.relays'),'Actuadores asignados visibles a administrador');
assert(app.includes('api("/api/control"'),'Mandos originales usan permisos vigentes');
assert(sw.includes('reles-ayn-v183-clear-admin-folder'));
assert(sw.includes('/app.js?v=20261008-voice181'));
console.log('Relés originales y gestionados listados; asignación sin duplicar, acceso de administrador y PWA verificados.');
