const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');
let registry={masterId:'phone-master-000001',masterIds:['notebook-master-0001'],devices:{'phone-master-000001':{role:'super_master',status:'active',relays:[1,2,3]},'notebook-master-0001':{role:'super_master',status:'active',relays:[1,2,3]},'ordinary-user-000001':{role:'super_master',status:'active',relays:[1]}},revoked:{}};
const m={exports:{}};vm.runInNewContext(fs.readFileSync('lib/devices.js','utf8'),{module:m,require,process:{env:{APP_PIN:'test-pin',KV_REST_API_URL:'test',KV_REST_API_TOKEN:'test'}},Buffer,fetch:async(u,o)=>{const a=JSON.parse(o.body);if(a[0]==='SET')registry=JSON.parse(a[2]);return {ok:true,json:async()=>({result:a[0]==='GET'?JSON.stringify(registry):'OK'})};}});
const access=(id,pin='test-pin')=>m.exports.authorize({headers:{'x-app-pin':pin,'x-device-id':id,'x-device-name':id}},{masterOnly:true,allowRegistration:false});
(async()=>{
 assert.equal((await access('phone-master-000001')).role,'super_master');assert.equal((await access('notebook-master-0001')).role,'super_master');assert.equal((await access('ordinary-user-000001')).ok,false);assert.equal(registry.devices['ordinary-user-000001'].role,'user');assert.equal((await access('new-notebook-000001')).ok,false);assert.equal((await access('notebook-master-0001','wrong')).status,401);
 registry.devices['notebook-master-0001'].status='paused';assert.equal((await access('notebook-master-0001')).ok,false);assert.equal((await access('phone-master-000001')).ok,true);registry.devices['notebook-master-0001'].status='active';assert.equal((await access('notebook-master-0001')).ok,true);
 let auth={role:'super_master',device:{id:registry.masterId},registry};const values=new Map();const A={error:(message,status=400)=>Object.assign(new Error(message),{status}),hash:s=>crypto.createHash('sha256').update(s).digest('hex'),token:()=>crypto.randomBytes(32).toString('hex'),access:async()=>auth,manager:a=>{if(!['admin','super_master'].includes(a.role))throw A.error('Solo administradores',403);},group:()=>'',redis:async(c,k,v)=>{if(c==='SET')values.set(k,v);if(c==='GET')return values.get(k);if(c==='DEL')values.delete(k);},updateRegistry:async fn=>fn(registry)};
 const endpoint={exports:{}};vm.runInNewContext(fs.readFileSync('api/administrations.js','utf8'),{module:endpoint,require:n=>n==='../lib/administrations'?A:n==='../lib/tuya'?{checkPin:r=>r.headers['x-app-pin']==='test-pin'}:n==='../lib/actuator-timers'?{}:{addHistory:async()=>{}}});
 async function req(body,id=registry.masterId,pin='test-pin'){let status=200,data;await endpoint.exports({method:'POST',body,headers:{'x-device-id':id,'x-app-pin':pin,'x-device-name':'Notebook Osvaldo'}},{setHeader(){},status(n){status=n;return this;},json(v){data=v;}});return {status,data};}
 auth.role='admin';assert.equal((await req({action:'invite',role:'super_master',name:'PC',phone:'56985802197'})).status,403);auth.role='super_master';
 const invitation=await req({action:'invite',role:'super_master',name:'Notebook',phone:'56985802197'});assert.equal(invitation.status,200);const token=invitation.data.token;const id='new-notebook-000001';
 assert.equal((await req({action:'claim',token},id,'wrong')).status,401);assert.equal((await req({action:'claim',token},registry.masterId)).status,403);
 assert.equal((await req({action:'claim',token},id)).status,200);assert(registry.masterIds.includes(id));assert.equal(registry.devices[id].role,'super_master');assert.equal(registry.devices[registry.masterId].role,'super_master');assert.deepEqual(Array.from(registry.devices[id].relays),[1,2,3]);
 assert.equal((await req({action:'claim',token},'other-notebook-0001')).status,410);assert.equal((await access(id)).role,'super_master');
 console.log('Dos Máster: celular conservado, alta por invitación única, PIN, pausa y prevención de escalada correctos.');
})().catch(e=>{console.error(e);process.exitCode=1});
