const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let generated=0,key,deleted=[],sent=[];const subscription={endpoint:'https://fcm.googleapis.com/test',keys:{p256dh:'a'.repeat(87),auth:'b'.repeat(22)}};
const devices={sender:{status:'active',groupId:'A'},recipient:{status:'active',groupId:'A'},other:{status:'active',groupId:'B'},paused:{status:'paused',groupId:'A'},expired:{status:'active',groupId:'A'}};
const rows=Object.keys(devices).flatMap(id=>[id,JSON.stringify({deviceId:id,subscription:{...subscription,endpoint:subscription.endpoint+'/'+id}})]);
devices.owner={role:'admin',groupId:'A',status:'active'};
const A={error:m=>new Error(m),redis:async(...a)=>{if(a[0]==='GET')return key;if(a[0]==='SET'){key=key||a[2];return'OK';}if(a[0]==='HGETALL')return rows;if(a[0]==='HDEL')deleted.push(a[2]);}};
const webpush={generateVAPIDKeys:()=>{generated++;return{publicKey:'public',privateKey:'private'};},sendNotification:async(s,p,o)=>{sent.push({s,p:JSON.parse(p),o});if(s.endpoint.endsWith('/expired'))throw{statusCode:410};}};
const moduleMock={exports:{}};vm.runInNewContext(fs.readFileSync('lib/panic-push.js','utf8'),{module:moduleMock,URL,require:n=>n==='./administrations'?A:webpush});const P=moduleMock.exports;
(async()=>{await P.keys();await P.keys();assert.equal(generated,1);P.validate(subscription);for(const endpoint of ['http://fcm.googleapis.com/x','https://127.0.0.1/x','https://fcm.googleapis.com.evil.test/x','https://user@fcm.googleapis.com/x'])assert.throws(()=>P.validate({...subscription,endpoint}));const alert={id:'event',groupId:'A',creator:'sender',name:'Vecino',expiresAt:new Date(Date.now()+300000).toISOString()};await P.send(alert,{registry:{devices}});assert.equal(sent.length,2);assert(sent.every(e=>e.s.endpoint.endsWith('/recipient')||e.s.endpoint.endsWith('/expired')));assert.deepEqual(deleted,['expired']);assert(sent[0].o.TTL<=300);await P.send(alert,{registry:{devices}},true);assert(sent.at(-1).p.cancelled);const before=sent.length;devices.owner.status='paused';await P.send(alert,{registry:{devices}});assert.equal(sent.length,before);const sw=fs.readFileSync('sw.js','utf8');assert(sw.includes("addEventListener('push'"));assert(sw.includes('showNotification'));console.log('Push: claves estables, endpoints seguros, administración aislada, usuarios activos, exclusión del emisor, caducidad y cancelación verificadas.');})().catch(e=>{console.error(e);process.exitCode=1;});
