const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),path=require('node:path');
let auth,fail=false,calls=0,commands;const values=new Map(),feeds=new Map(),config=new Map([['group-A',JSON.stringify({actuatorId:'act-A'})],['group-B',JSON.stringify({actuatorId:'act-B'})]]);
const records=[{id:'act-A',groupId:'group-A',approved:true,code:'switch_1',deviceId:'device-A',name:'Sirena A',timer:{code:'countdown_1'},timerSeconds:5},{id:'act-B',groupId:'group-B',approved:true,code:'switch_1',deviceId:'device-B',name:'Sirena B',timer:null,timerSeconds:0}];
const redis=async(...a)=>{if(a[0]==='HGET')return config.get(a[2]);if(a[0]==='HSET'){config.set(a[2],a[3]);return 1;}if(a[0]==='GET')return values.get(a[1]);if(a[0]==='MGET')return a.slice(1).map(k=>values.get(k)||null);if(a[0]==='LRANGE')return (feeds.get(a[1])||[]).slice(0,20);if(a[0]==='EVAL'){const script=a[1];if(script.includes("redis.call('EXISTS'")){if(values.has(a[3]))return 0;values.set(a[3],a[5]);feeds.set(a[4],[a[6],...(feeds.get(a[4])||[])]);return 1;}const old=values.get(a[3]);if(!old)return 0;const e=JSON.parse(old);if(script.includes('e.apology')){if(e.apology)return 2;e.apology=JSON.parse(a[4]);}else e.actuatorStatus=a[4];values.set(a[3],JSON.stringify(e));return 1;}throw new Error('Redis no simulado '+a[0]);};
const A={access:async()=>auth,group:(auth,g)=>{if(!['master','group-A','group-B'].includes(g))throw A.error('Grupo inválido');return g;},records:async()=>records,redis,error:(m,status=400)=>Object.assign(new Error(m),{status}),hash:x=>crypto.createHash('sha256').update(x).digest('hex'),seconds:n=>n};
const moduleMock={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../api/panic.js'),'utf8'),{module:moduleMock,require:n=>n==='../lib/administrations'?A:n==='../lib/timed-command'?{runTimed:async(id,code,state,seconds,timer)=>{calls++;commands=[{code,value:state},{code:timer?.code,value:seconds}];if(fail)throw Error('Offline');return {state:false};}}:{getToken:async()=>'token',tuyaFetch:async(method,p,body)=>{calls++;commands=JSON.parse(body).commands;if(fail)throw new Error('Offline');}}});
function login(role,id,groupId){auth={role,groupId,device:{id,name:id},registry:{devices:{[id]:{adminName:id,phone:'56912345678',apartment:'204'}}}};}
async function request(body,method='POST',query={}){let value,status=200;const res={setHeader(){},status(n){status=n;return this;},json(v){value=v;}};await moduleMock.exports({body,method,query},res);return {status,value};}
(async()=>{let n=0;const check=v=>{assert(v);n++;};login('user','user-A','group-A');
check((await request({action:'configure',groupId:'group-A',actuatorId:'act-A'})).status===403);
check((await request({action:'trigger',groupId:'group-B',requestId:'request-0000000001'})).status===403);check(calls===0);
const first=await request({action:'trigger',groupId:'group-A',requestId:'request-0000000001'});check(first.status===200);check(Math.abs(Date.parse(first.value.expiresAt)-Date.now()-300000)<1000);check(first.value.actuatorStatus==='sent');check(commands[0].value===true);check(commands[1].value===5);
check((await request({action:'trigger',groupId:'group-A',requestId:'request-0000000001'})).value.duplicate===true);check(calls===1);
let feed=await request({},'GET',{groupId:'group-A'});check(feed.value.events.length===1);check(feed.value.events[0].canApologize===true);check(feed.value.events[0].name==='user-A');check(feed.value.events[0].phone==='56912345678');check(feed.value.events[0].apartment==='204');
login('user','user-other','group-A');check((await request({action:'apologize',groupId:'group-A',eventId:first.value.eventId})).status===403);
login('admin','admin-A','group-A');check((await request({action:'apologize',groupId:'group-A',eventId:first.value.eventId})).status===200);
feed=await request({},'GET',{groupId:'group-A'});check(feed.value.events[0].apology.message.includes('accidentalmente'));check(feed.value.events[0].actuatorStatus==='sent');
login('user','user-B','group-B');feed=await request({},'GET',{groupId:'group-B'});check(feed.value.events.length===0);check((await request({action:'apologize',groupId:'group-B',eventId:first.value.eventId})).status===403);
fail=true;const failure=await request({action:'trigger',groupId:'group-B',requestId:'request-0000000002'});check(failure.value.actuatorStatus==='failed');feed=await request({},'GET',{groupId:'group-B'});check(feed.value.events.length===1);
login('super_master','master','');check((await request({action:'configure',groupId:'group-A',actuatorId:'act-B'})).status===400);check((await request({action:'configure',groupId:'group-A',actuatorId:'act-A'})).status===200);
console.log(n+' comprobaciones de pánico, aislamiento, disculpas y fallo de actuador correctas');
})().catch(e=>{console.error(e);process.exitCode=1});
