const A=require('./administrations'),webpush=require('web-push');
const KEY='ayn:panic:push:keys',SUBS='ayn:panic:push:subscriptions';
async function keys(){let raw=await A.redis('GET',KEY);if(!raw){await A.redis('SET',KEY,JSON.stringify(webpush.generateVAPIDKeys()),'NX');raw=await A.redis('GET',KEY);}return JSON.parse(raw);}
function validate(subscription){let url;try{url=new URL(subscription?.endpoint);}catch{throw A.error('Suscripción inválida.');}const allowed=url.hostname==='fcm.googleapis.com'||url.hostname==='updates.push.services.mozilla.com'||url.hostname==='web.push.apple.com';if(url.protocol!=='https:'||url.port||url.username||url.password||!allowed||url.href.length>2048||!/^[-_A-Za-z0-9]{80,100}$/.test(subscription?.keys?.p256dh||'')||!/^[-_A-Za-z0-9]{20,30}$/.test(subscription?.keys?.auth||''))throw A.error('Servicio de notificaciones no compatible o suscripción inválida.');return {endpoint:url.href,keys:{p256dh:subscription.keys.p256dh,auth:subscription.keys.auth}};}
async function send(alert,auth,cancelled=false){const owner=alert.groupId==='master'?auth.registry.devices[auth.registry.masterId]:Object.values(auth.registry.devices).find(d=>d.role==='admin'&&d.groupId===alert.groupId);if(!owner||owner.status!=='active')return;const raw=await A.redis('HGETALL',SUBS),vapid=await keys();const jobs=[];for(let i=0;i<(raw||[]).length;i+=2){let record;try{record=JSON.parse(raw[i+1]);}catch{continue;}const person=auth.registry.devices[record.deviceId],group=person?.groupId||(record.deviceId===auth.registry.masterId?'master':null);if(!person||person.status!=='active'||group!==alert.groupId||record.deviceId===alert.creator)continue;jobs.push({field:raw[i],subscription:record.subscription});}
 const payload=JSON.stringify({id:alert.id,cancelled,title:cancelled?'SOS cancelado':'ALERTA SOS · AYN',body:cancelled?'La alerta fue cancelada por activación accidental.':`${alert.name} solicita ayuda. Departamento: ${alert.apartment||'sin registrar'}. Teléfono: ${alert.phone||'sin registrar'}.`,expiresAt:alert.expiresAt});
 for(let i=0;i<jobs.length;i+=50)await Promise.allSettled(jobs.slice(i,i+50).map(async job=>{try{await webpush.sendNotification(job.subscription,payload,{vapidDetails:{subject:'https://rele-control-ayn.vercel.app',...vapid},TTL:cancelled?60:Math.max(0,Math.ceil((Date.parse(alert.expiresAt)-Date.now())/1000)),urgency:'high',timeout:3000});}catch(e){if([404,410].includes(e.statusCode))await A.redis('HDEL',SUBS,job.field);}}));
}
module.exports={keys,validate,send,SUBS};
